language: c
sudo: requried
dist: trusty

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y gettext

install:
    - wget https://sourceforge.net/projects/dos2unix/files/dos2unix/7.3.4/dos2unix-7.3.4.tar.gz/download -O dos2unix.tar.gz
    - tar xf dos2unix.tar.gz
    - cd dos2unix-7.3.4 && make && sudo make prefix=/usr install
    - cd ..

script:
    # Be permissive, unset following enviroment
    - export STRICT_HOSTS_FORMAT=1
    - bash tools/checkhosts.sh
